function ExoticFormBreeds() {
  const exoticBreeds = [
    "Amazon Parrot",
    "Ant",
    "Badger",
    "Ball Python",
    "Bat",
    "Bearded Dragon",
    "Beaver",
    "Bicheno's Diamond",
    "Black-headed Conure",
    "Black-necked Grebe",
    "Blue-and-yellow Macaw",
    "Blue-crowned Conure",
    "Blue-fronted Amazon",
    "Blue-headed Parrot",
    "Boa",
    "Bourke's Parakeet",
    "Buffon's Macaw",
    "Buzzard",
    "Canary",
    "Carp",
    "Catfish",
    "Chaffinch",
    "Chicken",
    "Chinese Hamster",
    "Chinchilla",
    "Cockatiel",
    "Cockatoos",
    "Common Wood Pigeon",
    "Coot",
    "Cormorant",
    "Cow",
    "Crow",
    "Deer",
    "Degu",
    "Doe",
    "Dolphin",
    "Domestic Cow",
    "Dormouse",
    "Draft Horse",
    "Duck",
    "Dwarf Cow",
    "Dwarf Goat",
    "Dwarf Rabbit",
    "Eclectus Parrot",
    "Egret",
    "Elegant Parakeet",
    "European Greenfinch",
    "Fauve de Bourgogne Rabbit",
    "Ferret",
    "Flemish Giant Rabbit",
    "Flamingo",
    "Fox",
    "Frantz's Kite",
    "Giant Butterfly Rabbit",
    "Goldfinch",
    "Goldfish",
    "Goat",
    "Goose",
    "Grand Noir du Berry Donkey",
    "Green Iguana",
    "Green-cheeked Conure",
    "Guinea Fowl",
    "Guinea Pig",
    "Gudgeon",
    "Gerbil",
    "Great Spotted Woodpecker",
    "Guppy (Fish)",
    "Hare",
    "Hedgehog",
    "Helmeted Chameleon",
    "Heron",
    "Hoopoe",
    "Jardine's Parrot",
    "Japanese Sparrow",
    "Jay",
    "Kangaroo",
    "Kestrel",
    "Kingfisher",
    "Korean Squirrel",
    "Land Turtle",
    "Leopard Gecko",
    "Lesser Spotted Woodpecker",
    "Llama",
    "Lovebird",
    "Macaque",
    "Magpie",
    "Mandarin Duck",
    "Marten",
    "Macaw",
    "Monkey",
    "Monk Parakeet",
    "Moose",
    "Moustached Parakeet",
    "New Caledonian Parakeet",
    "Netherland Dwarf Rabbit",
    "Ornamental Pigeon",
    "Ostrich",
    "Ouessant Sheep",
    "Owl",
    "Owls",
    "Pangolin",
    "Parakeet",
    "Patagonian Conure",
    "Peacock",
    "Peregrine Falcon",
    "Pheasant",
    "Pig",
    "Pigeon",
    "Polecat",
    "Pony",
    "Poitou Donkey",
    "Prairie Dog",
    "Quail",
    "Quaker Parrot",
    "Rabbit",
    "Raccoon",
    "Raven",
    "Red-fronted Conure",
    "Red-fronted Kakariki",
    "Ring-necked Parakeet",
    "Roborovski Hamster",
    "Rock Pigeon",
    "Robin",
    "Roe Deer",
    "Russian Hamster",
    "Saddle Horse",
    "Salamander",
    "Scarlet Macaw",
    "Scorpion",
    "Seagull",
    "Senegal Parrot",
    "Sheep",
    "Shetland Pony",
    "Sparrow",
    "Snake",
    "Snail",
    "Squirrel",
    "Starling",
    "Stork",
    "Swallow",
    "Swan",
    "Swift",
    "Swordfish",
    "Turtle",
    "Turtle Dove",
    "Turkey",
    "Timneh Parrot",
    "Titmouse",
    "Viper",
    "Vietnamese Pig",
    "Wallaby",
    "Water Hen",
    "Weasel",
    "White-bellied Caique",
    "Wild Boar",
    "Wild Mouse",
    "Wild Rat",
    "Woodcock",
    "Woodpecker",
    "Yemeni Helmeted Chameleon",
  ];
  return (
    <>
      <option value="" disabled>
        Select the exotic breed
      </option>
      {exoticBreeds.map((breed) => {
        return (
          <option key={breed} value={breed}>
            {breed}
          </option>
        );
      })}
    </>
  );
}

export default ExoticFormBreeds;
